# morphisms/weights.py
from morphisms.exact import (
    inherit_weights, 
    inherit_weights_net2wider, 
    initialize_conv_as_identity, 
    initialize_bn_as_identity
)
from morphisms.approximate import inherit_weights_prune, inherit_weights_sepconv

def transfer_weights(parent_model, child_model, op_name, target_info):
    """
    Master router for Lamarckian weight inheritance.
    Copies unmodified weights first, then applies specific morphism math.
    """
    # 1. Base Inheritance: Safely copy all layers that share identical shapes/keys
    inherit_weights(parent_model, child_model)
    
    # 2. Operator-Specific Inheritance Math
    if target_info is None:
        return
        
    target_node = target_info.get("target_node")
    
    if op_name == "net2deeper":
        # Pull the exact predicted IDs generated by operators.py
        conv_key = str(target_info.get("new_conv_id"))
        bn_key = str(target_info.get("new_bn_id"))
        
        # Initialize the new layers as identity pass-throughs
        if conv_key in child_model.layers:
            initialize_conv_as_identity(child_model.layers[conv_key])
            
        if bn_key in child_model.layers:
            initialize_bn_as_identity(child_model.layers[bn_key])
            
    elif op_name == "net2wider" and target_node is not None:
        inherit_weights_net2wider(parent_model, child_model, target_node, widen_by=4)
        
    elif op_name == "prune" and target_node is not None:
        inherit_weights_prune(parent_model, child_model, target_node)
        
    elif op_name == "sepconv" and target_node is not None:
        inherit_weights_sepconv(parent_model, child_model, target_node)